version: "3.8"

services:
  bison-homepage:
    image: nginx:alpine
    container_name: bison-homepage
    restart: unless-stopped
    hostname: bison-homepage
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      br0:
        ipv4_address: 10.0.101.65

networks:
  br0:
    external: true
    name: br0
